### ISSUE TITLE
Update PHP Examples 

### ISSUE THREAD

**Issue by LorenzBuehmann** [AKSW/DL-Learner#27]
Some of the PHP examples to show the web service feature need to be refactored.

Location: ./php-examples

The problem is in the Utitlities.php file, which includes some HTTP library that does not exist in the examples folder.

A solution would be to replace it by

a) some more common lib which is accessible via standard PHP package manager
b) add the lib file to the php-examples folder

**Comment by SimonBin** [comment]
would it be sensible to remove php altogether and replace it with python?

**Comment by patrickwestphal** [comment]
@SimonBin +1 from my side. (Who would have expected... ;) )
I think the problem is, that most of us do not (want to) have deeper insights in PHP and the PHP files are 6-7 years old which makes them hard to maintain, now.
But I would not start until this decision is backed by the majority of us. Also I can't really estimate if the porting to Python would need less time than fixing the PHP scripts. So maybe we can postpone a port to later releases and try to fix things for now.

**Comment by JensLehmann** [comment]
I have nothing against using Python for the examples instead of PHP. The web service should be usable from arbitrary languages and demonstrating that using at least one popular non-Java language should be fine. 

Looking at Utilities.php it contains some workarounds (like manually loading a WSDL files) which should ideally not be needed. It is not used by the LearningSimple and LearningClass files.

**Comment by patrickwestphal** [comment]
Repaired the PHP examples.
